// Generated by unRap v1.06 by Kegetys

class Stage5 {
	texture = "a3\characters_f_bootcamp\common\data\vrarmor_smdi.paa";
	uvSource = "tex";
	
	class uvTransform {
		aside[] = {1, 0, 0};
		up[] = {0, 1, 0};
		dir[] = {0, 0, 0};
		pos[] = {0, 0, 0};
	};
};
