// Generated by unRap v1.06 by Kegetys

class Stage4 {
	texture = "#(argb,8,8,3)color(1.0,1.0,1.0,1.0,AS)";
	uvSource = "tex";
	
	class uvTransform {
		aside[] = {1, 0, 0};
		up[] = {0, 1, 0};
		dir[] = {0, 0, 0};
		pos[] = {0, 0, 0};
	};
};
