// Generated by unRap v1.06 by Kegetys

class Stage1 {
	texture = "#(argb,8,8,3)color(0.5,0.5,1,1,NOHQ)";
	uvSource = "tex";
	
	class uvTransform {
		aside[] = {1, 0, 0};
		up[] = {0, 1, 0};
		dir[] = {0, 0, 0};
		pos[] = {0, 0, 0};
	};
};
